install.packages(setdiff(
  c("doSNOW", "tictoc", "gtools", "sirt"),
  rownames(installed.packages())
))

source("../utils.r")
source("../cogom.r")
library(doSNOW)
library(gtools)
library(tictoc)
library(sirt)

## parallel computing parameters
numCores <- 32L
cl <- makeCluster(numCores)
registerDoSNOW(cl)

# parallel experiments
m <- 100 

## each row of Pi is generated by Dirichlet(1,1,...,1)
pi_gen <- function(pi, K) {
  rdirichlet(1, rep(1, K))
}

# return mean absolute difference of Pi and Theta, as well as running time for JML, Null and Covariate-assisted
GoM_simulate <- function(A, X, K, Pi, Theta) {
  ## JML
  tic()
  jml.est <- gom.jml(data.frame(A), K)
  jml.time <- toc()
  jml.time <- jml.time$toc - jml.time$tic
  Pi.jml <- as.matrix(jml.est$g)
  Theta.jml <- as.matrix(jml.est$lambda[, 3:(K + 2)])
  idx.jml <- find_best_idx(K, Pi.jml, Pi)
  pi.err.jml <- mean(abs(Pi.jml[, idx.jml] - Pi))
  theta.err.jml <- mean(abs(Theta.jml[, idx.jml] - Theta))
  pi.err2.jml <- max(apply(Pi.jml[, idx.jml] - Pi, 1, norm, "2"))
  theta.err2.jml <- max(apply(Theta.jml[, idx.jml] - Theta, 1, norm, "2"))

  ## Null
  tic()
  null.est <- gom.svd(A, K)
  svd.time <- toc()
  svd.time <- svd.time$toc - svd.time$tic
  idx.null <- find_best_idx(null.est$Pi, Pi)
  pi.err.svd <- mean(abs(null.est$Pi[, idx.null] - Pi))
  theta.err.svd <- mean(abs(null.est$Theta[, idx.null] - Theta))
  pi.err2.svd <- max(apply(null.est$Pi[, idx.null] - Pi, 1, norm, "2"))
  theta.err2.svd <- max(apply(null.est$Theta[, idx.null] - Theta, 1, norm, "2"))

  ## Covariate-assisted include the time of finding alpha
  # alpha_seq = seq(from=0,to=1,length=100)
  tic()
  alpha <- find_best_alpha(alpha_seq, A, X, K) # the code needs modification
  hetero.est <- gom.cov(A, X, K, alpha)
  hetero.time <- toc()
  hetero.time <- hetero.time$toc - hetero.time$tic
  idx.hetero <- find_best_idx(hetero.est$Pi, Pi)
  pi.err.hetero <- mean(abs(hetero.est$Pi[, idx.hetero] - Pi))
  theta.err.hetero <- mean(abs(hetero.est$Theta[, idx.null] - Theta))
  pi.err2.hetero <- max(apply(hetero.est$Pi[, idx.hetero] - Pi, 1, norm, "2"))
  theta.err2.hetero <- max(apply(ov.est$Theta[, idx.hetero] - Theta, 1, norm, "2"))

  res <- list(
    jml.pi = pi.err.jml, jml.theta = theta.err.jml, jml.time = jml.time,
    jml.pi2 = pi.err2.jml, jml.theta = theta.err2.jml,
    svd.pi = pi.err.svd, svd.theta = theta.err.svd, svd.time = svd.time,
    svd.pi2 = pi.err2.svd, svd.theta = theta.err2.svd,
    hetero.pi = pi.err.hetero, hetero.theta = theta.err.hetero, 
    hetero.time = hetero.time, hetero.pi2 = pi.err2.hetero, 
    hetero.theta2 = theta.err2.hetero, alpha = alpha
  )

  res
}

# N=200,K=3 Simulation
res_N200_K3 <- foreach(i = 1:m, .combine = rbind, .packages = c("sirt", "gtools", "tictoc")) %dopar% {
  set.seed(i)
  N <- 200
  K <- 3
  J <- N / 10
  W <- N / 20

  # generate values
  Pi <- matrix(rep(0, N * K), nrow = N)
  Pi <- t(apply(Pi, 1, pi_gen, K = K))
  Theta <- matrix(runif(J * K), ncol = K)
  M <- matrix(rnorm(W * K, 0, 1), nrow = W)
  Pi[1:K, ] <- diag(rep(1, K))

  A_t <- Pi %*% t(Theta)
  X_t <- Pi %*% t(M)

  A <- matrix(rbinom(N * J, 1, A_t), nrow = N)
  X <- X_t + matrix(rnorm(N * W, 0, .5), nrow = N)
  X <- apply(X, 2, scale)

  GoM_simulate(A, X, K, Pi, Theta)
}

# N=500,K=3 Simulation
res_N500_K3 <- foreach(i = 1:m, .combine = rbind, .packages = c("sirt", "gtools", "tictoc")) %dopar% {
  set.seed(i)
  N <- 500
  K <- 3
  J <- N / 10
  W <- N / 20

  # generate values
  Pi <- matrix(rep(0, N * K), nrow = N)
  Pi <- t(apply(Pi, 1, pi_gen, K = K))
  Theta <- matrix(runif(J * K), ncol = K)
  M <- matrix(rnorm(W * K, 0, 1), nrow = W)
  Pi[1:K, ] <- diag(rep(1, K))

  A_t <- Pi %*% t(Theta)
  X_t <- Pi %*% t(M)

  A <- matrix(rbinom(N * J, 1, A_t), nrow = N)
  X <- X_t + matrix(rnorm(N * W, 0, .5), nrow = N)
  X <- apply(X, 2, scale)

  GoM_simulate(A, X, K, Pi, Theta)
}

# N=1000,K=3 Simulation
res_N1000_K3 <- foreach(i = 1:m, .combine = rbind, .packages = c("sirt", "gtools", "tictoc")) %dopar% {
  set.seed(i)
  N <- 1000
  K <- 3
  J <- N / 10
  W <- N / 20

  # generate values
  Pi <- matrix(rep(0, N * K), nrow = N)
  Pi <- t(apply(Pi, 1, pi_gen, K = K))
  Theta <- matrix(runif(J * K), ncol = K)
  M <- matrix(rnorm(W * K, 0, 1), nrow = W)
  Pi[1:K, ] <- diag(rep(1, K))

  A_t <- Pi %*% t(Theta)
  X_t <- Pi %*% t(M)

  A <- matrix(rbinom(N * J, 1, A_t), nrow = N)
  X <- X_t + matrix(rnorm(N * W, 0, .5), nrow = N)
  X <- apply(X, 2, scale)

  GoM_simulate(A, X, K, Pi, Theta)
}

# N=2000,K=3 Simulation
res_N2000_K3 <- foreach(i = 1:m, .combine = rbind, .packages = c("sirt", "gtools", "tictoc")) %dopar% {
  set.seed(i)
  N <- 2000
  K <- 3
  J <- N / 10
  W <- N / 20

  # generate values
  Pi <- matrix(rep(0, N * K), nrow = N)
  Pi <- t(apply(Pi, 1, pi_gen, K = K))
  Theta <- matrix(runif(J * K), ncol = K)
  M <- matrix(rnorm(W * K, 0, 1), nrow = W)
  Pi[1:K, ] <- diag(rep(1, K))

  A_t <- Pi %*% t(Theta)
  X_t <- Pi %*% t(M)

  A <- matrix(rbinom(N * J, 1, A_t), nrow = N)
  X <- X_t + matrix(rnorm(N * W, 0, .5), nrow = N)
  X <- apply(X, 2, scale)

  GoM_simulate(A, X, K, Pi, Theta)
}

# N=5000,K=3 Simulation
res_N5000_K3 <- foreach(i = 1:m, .combine = rbind, .packages = c("sirt", "gtools", "tictoc")) %dopar% {
  set.seed(i)
  N <- 5000
  K <- 3
  J <- N / 10
  W <- N / 20

  # generate values
  Pi <- matrix(rep(0, N * K), nrow = N)
  Pi <- t(apply(Pi, 1, pi_gen, K = K))
  Theta <- matrix(runif(J * K), ncol = K)
  M <- matrix(rnorm(W * K, 0, 1), nrow = W)
  Pi[1:K, ] <- diag(rep(1, K))

  A_t <- Pi %*% t(Theta)
  X_t <- Pi %*% t(M)

  A <- matrix(rbinom(N * J, 1, A_t), nrow = N)
  X <- X_t + matrix(rnorm(N * W, 0, .5), nrow = N)
  X <- apply(X, 2, scale)

  GoM_simulate(A, X, K, Pi, Theta)
}

# N=200,K=8 Simulation
res_N200_K8 <- foreach(i = 1:m, .combine = rbind, .packages = c("sirt", "gtools", "tictoc")) %dopar% {
  set.seed(i)
  N <- 200
  K <- 8
  J <- N / 10
  W <- N / 20

  # generate values
  Pi <- matrix(rep(0, N * K), nrow = N)
  Pi <- t(apply(Pi, 1, pi_gen, K = K))
  Theta <- matrix(runif(J * K), ncol = K)
  M <- matrix(rnorm(W * K, 0, 1), nrow = W)
  Pi[1:K, ] <- diag(rep(1, K))

  A_t <- Pi %*% t(Theta)
  X_t <- Pi %*% t(M)

  A <- matrix(rbinom(N * J, 1, A_t), nrow = N)
  X <- X_t + matrix(rnorm(N * W, 0, .5), nrow = N)
  X <- apply(X, 2, scale)

  GoM_simulate(A, X, K, Pi, Theta)
}

# N=500,K=8 Simulation
res_N500_K8 <- foreach(i = 1:m, .combine = rbind, .packages = c("sirt", "gtools", "tictoc")) %dopar% {
  set.seed(i)
  N <- 500
  K <- 8
  J <- N / 10
  W <- N / 20

  # generate values
  Pi <- matrix(rep(0, N * K), nrow = N)
  Pi <- t(apply(Pi, 1, pi_gen, K = K))
  Theta <- matrix(runif(J * K), ncol = K)
  M <- matrix(rnorm(W * K, 0, 1), nrow = W)
  Pi[1:K, ] <- diag(rep(1, K))

  A_t <- Pi %*% t(Theta)
  X_t <- Pi %*% t(M)

  A <- matrix(rbinom(N * J, 1, A_t), nrow = N)
  X <- X_t + matrix(rnorm(N * W, 0, .5), nrow = N)
  X <- apply(X, 2, scale)

  GoM_simulate(A, X, K, Pi, Theta)
}

# N=1000,K=8 Simulation
res_N1000_K8 <- foreach(i = 1:m, .combine = rbind, .packages = c("sirt", "gtools", "tictoc")) %dopar% {
  set.seed(i)
  N <- 1000
  K <- 8
  J <- N / 10
  W <- N / 20

  # generate values
  Pi <- matrix(rep(0, N * K), nrow = N)
  Pi <- t(apply(Pi, 1, pi_gen, K = K))
  Theta <- matrix(runif(J * K), ncol = K)
  M <- matrix(rnorm(W * K, 0, 1), nrow = W)
  Pi[1:K, ] <- diag(rep(1, K))

  A_t <- Pi %*% t(Theta)
  X_t <- Pi %*% t(M)

  A <- matrix(rbinom(N * J, 1, A_t), nrow = N)
  X <- X_t + matrix(rnorm(N * W, 0, .5), nrow = N)
  X <- apply(X, 2, scale)

  GoM_simulate(A, X, K, Pi, Theta)
}

# N=2000,K=8 Simulation
res_N2000_K8 <- foreach(i = 1:m, .combine = rbind, .packages = c("sirt", "gtools", "tictoc")) %dopar% {
  set.seed(i)
  N <- 2000
  K <- 8
  J <- N / 10
  W <- N / 20

  # generate values
  Pi <- matrix(rep(0, N * K), nrow = N)
  Pi <- t(apply(Pi, 1, pi_gen, K = K))
  Theta <- matrix(runif(J * K), ncol = K)
  M <- matrix(rnorm(W * K, 0, 1), nrow = W)
  Pi[1:K, ] <- diag(rep(1, K))

  A_t <- Pi %*% t(Theta)
  X_t <- Pi %*% t(M)

  A <- matrix(rbinom(N * J, 1, A_t), nrow = N)
  X <- X_t + matrix(rnorm(N * W, 0, .5), nrow = N)
  X <- apply(X, 2, scale)

  GoM_simulate(A, X, K, Pi, Theta)
}

# N=5000,K=8 Simulation
res_N5000_K8 <- foreach(i = 1:m, .combine = rbind, .packages = c("sirt", "gtools", "tictoc")) %dopar% {
  set.seed(i)
  N <- 5000
  K <- 8
  J <- N / 10
  W <- N / 20

  # generate values
  Pi <- matrix(rep(0, N * K), nrow = N)
  Pi <- t(apply(Pi, 1, pi_gen, K = K))
  Theta <- matrix(runif(J * K), ncol = K)
  M <- matrix(rnorm(W * K, 0, 1), nrow = W)
  Pi[1:K, ] <- diag(rep(1, K))

  A_t <- Pi %*% t(Theta)
  X_t <- Pi %*% t(M)

  A <- matrix(rbinom(N * J, 1, A_t), nrow = N)
  X <- X_t + matrix(rnorm(N * W, 0, .5), nrow = N)
  X <- apply(X, 2, scale)

  GoM_simulate(A, X, K, Pi, Theta)
}

## Long J scenario
## J = 10N, W = 5N

# N=200,K=3 Simulation
res_N200_K3_long <- foreach(i = 1:m, .combine = rbind, .packages = c("sirt", "gtools", "tictoc")) %dopar% {
  set.seed(i)
  N <- 200
  K <- 3
  J <- N * 10
  W <- N * 5

  # generate values
  Pi <- matrix(rep(0, N * K), nrow = N)
  Pi <- t(apply(Pi, 1, pi_gen, K = K))
  Theta <- matrix(runif(J * K), ncol = K)
  M <- matrix(rnorm(W * K, 0, 1), nrow = W)
  Pi[1:K, ] <- diag(rep(1, K))

  A_t <- Pi %*% t(Theta)
  X_t <- Pi %*% t(M)

  A <- matrix(rbinom(N * J, 1, A_t), nrow = N)
  X <- X_t + matrix(rnorm(N * W, 0, .5), nrow = N)
  X <- apply(X, 2, scale)

  GoM_simulate(A, X, K, Pi, Theta)
}

# N=500,K=3 Simulation
res_N500_K3_long <- foreach(i = 1:m, .combine = rbind, .packages = c("sirt", "gtools", "tictoc")) %dopar% {
  set.seed(i)
  N <- 500
  K <- 3
  J <- N * 10
  W <- N * 5

  # generate values
  Pi <- matrix(rep(0, N * K), nrow = N)
  Pi <- t(apply(Pi, 1, pi_gen, K = K))
  Theta <- matrix(runif(J * K), ncol = K)
  M <- matrix(rnorm(W * K, 0, 1), nrow = W)
  Pi[1:K, ] <- diag(rep(1, K))

  A_t <- Pi %*% t(Theta)
  X_t <- Pi %*% t(M)

  A <- matrix(rbinom(N * J, 1, A_t), nrow = N)
  X <- X_t + matrix(rnorm(N * W, 0, .5), nrow = N)
  X <- apply(X, 2, scale)

  GoM_simulate(A, X, K, Pi, Theta)
}

# N=1000,K=3 Simulation
res_N1000_K3_long <- foreach(i = 1:m, .combine = rbind, .packages = c("sirt", "gtools", "tictoc")) %dopar% {
  set.seed(i)
  N <- 1000
  K <- 3
  J <- N * 10
  W <- N * 5

  # generate values
  Pi <- matrix(rep(0, N * K), nrow = N)
  Pi <- t(apply(Pi, 1, pi_gen, K = K))
  Theta <- matrix(runif(J * K), ncol = K)
  M <- matrix(rnorm(W * K, 0, 1), nrow = W)
  Pi[1:K, ] <- diag(rep(1, K))

  A_t <- Pi %*% t(Theta)
  X_t <- Pi %*% t(M)

  A <- matrix(rbinom(N * J, 1, A_t), nrow = N)
  X <- X_t + matrix(rnorm(N * W, 0, .5), nrow = N)
  X <- apply(X, 2, scale)

  GoM_simulate(A, X, K, Pi, Theta)
}

# N=2000,K=3 Simulation
res_N2000_K3_long <- foreach(i = 1:m, .combine = rbind, .packages = c("sirt", "gtools", "tictoc")) %dopar% {
  set.seed(i)
  N <- 2000
  K <- 3
  J <- N * 10
  W <- N * 5

  # generate values
  Pi <- matrix(rep(0, N * K), nrow = N)
  Pi <- t(apply(Pi, 1, pi_gen, K = K))
  Theta <- matrix(runif(J * K), ncol = K)
  M <- matrix(rnorm(W * K, 0, 1), nrow = W)
  Pi[1:K, ] <- diag(rep(1, K))

  A_t <- Pi %*% t(Theta)
  X_t <- Pi %*% t(M)

  A <- matrix(rbinom(N * J, 1, A_t), nrow = N)
  X <- X_t + matrix(rnorm(N * W, 0, .5), nrow = N)
  X <- apply(X, 2, scale)

  GoM_simulate(A, X, K, Pi, Theta)
}

# N=5000,K=3 Simulation
res_N5000_K3_long <- foreach(i = 1:m, .combine = rbind, .packages = c("sirt", "gtools", "tictoc")) %dopar% {
  set.seed(i)
  N <- 5000
  K <- 3
  J <- N * 10
  W <- N * 5

  # generate values
  Pi <- matrix(rep(0, N * K), nrow = N)
  Pi <- t(apply(Pi, 1, pi_gen, K = K))
  Theta <- matrix(runif(J * K), ncol = K)
  M <- matrix(rnorm(W * K, 0, 1), nrow = W)
  Pi[1:K, ] <- diag(rep(1, K))

  A_t <- Pi %*% t(Theta)
  X_t <- Pi %*% t(M)

  A <- matrix(rbinom(N * J, 1, A_t), nrow = N)
  X <- X_t + matrix(rnorm(N * W, 0, .5), nrow = N)
  X <- apply(X, 2, scale)

  GoM_simulate(A, X, K, Pi, Theta)
}

# N=200,K=8 Simulation
res_N200_K8_long <- foreach(i = 1:m, .combine = rbind, .packages = c("sirt", "gtools", "tictoc")) %dopar% {
  set.seed(i)
  N <- 200
  K <- 8
  J <- N * 10
  W <- N * 5

  # generate values
  Pi <- matrix(rep(0, N * K), nrow = N)
  Pi <- t(apply(Pi, 1, pi_gen, K = K))
  Theta <- matrix(runif(J * K), ncol = K)
  M <- matrix(rnorm(W * K, 0, 1), nrow = W)
  Pi[1:K, ] <- diag(rep(1, K))

  A_t <- Pi %*% t(Theta)
  X_t <- Pi %*% t(M)

  A <- matrix(rbinom(N * J, 1, A_t), nrow = N)
  X <- X_t + matrix(rnorm(N * W, 0, .5), nrow = N)
  X <- apply(X, 2, scale)

  GoM_simulate(A, X, K, Pi, Theta)
}

# N=500,K=8 Simulation
res_N500_K8_long <- foreach(i = 1:m, .combine = rbind, .packages = c("sirt", "gtools", "tictoc")) %dopar% {
  set.seed(i)
  N <- 500
  K <- 8
  J <- N * 10
  W <- N * 5

  # generate values
  Pi <- matrix(rep(0, N * K), nrow = N)
  Pi <- t(apply(Pi, 1, pi_gen, K = K))
  Theta <- matrix(runif(J * K), ncol = K)
  M <- matrix(rnorm(W * K, 0, 1), nrow = W)
  Pi[1:K, ] <- diag(rep(1, K))

  A_t <- Pi %*% t(Theta)
  X_t <- Pi %*% t(M)

  A <- matrix(rbinom(N * J, 1, A_t), nrow = N)
  X <- X_t + matrix(rnorm(N * W, 0, .5), nrow = N)
  X <- apply(X, 2, scale)

  GoM_simulate(A, X, K, Pi, Theta)
}

# N=1000,K=8 Simulation
res_N1000_K8_long <- foreach(i = 1:m, .combine = rbind, .packages = c("sirt", "gtools", "tictoc")) %dopar% {
  set.seed(i)
  N <- 1000
  K <- 8
  J <- N * 10
  W <- N * 5

  # generate values
  Pi <- matrix(rep(0, N * K), nrow = N)
  Pi <- t(apply(Pi, 1, pi_gen, K = K))
  Theta <- matrix(runif(J * K), ncol = K)
  M <- matrix(rnorm(W * K, 0, 1), nrow = W)
  Pi[1:K, ] <- diag(rep(1, K))

  A_t <- Pi %*% t(Theta)
  X_t <- Pi %*% t(M)

  A <- matrix(rbinom(N * J, 1, A_t), nrow = N)
  X <- X_t + matrix(rnorm(N * W, 0, .5), nrow = N)
  X <- apply(X, 2, scale)

  GoM_simulate(A, X, K, Pi, Theta)
}

# N=2000,K=8 Simulation
res_N2000_K8_long <- foreach(i = 1:m, .combine = rbind, .packages = c("sirt", "gtools", "tictoc")) %dopar% {
  set.seed(i)
  N <- 2000
  K <- 8
  J <- N * 10
  W <- N * 5

  # generate values
  Pi <- matrix(rep(0, N * K), nrow = N)
  Pi <- t(apply(Pi, 1, pi_gen, K = K))
  Theta <- matrix(runif(J * K), ncol = K)
  M <- matrix(rnorm(W * K, 0, 1), nrow = W)
  Pi[1:K, ] <- diag(rep(1, K))

  A_t <- Pi %*% t(Theta)
  X_t <- Pi %*% t(M)

  A <- matrix(rbinom(N * J, 1, A_t), nrow = N)
  X <- X_t + matrix(rnorm(N * W, 0, .5), nrow = N)
  X <- apply(X, 2, scale)

  GoM_simulate(A, X, K, Pi, Theta)
}

# N=5000,K=8 Simulation
res_N5000_K8_long <- foreach(i = 1:m, .combine = rbind, .packages = c("sirt", "gtools", "tictoc")) %dopar% {
  set.seed(i)
  N <- 5000
  K <- 8
  J <- N * 10
  W <- N * 5

  # generate values
  Pi <- matrix(rep(0, N * K), nrow = N)
  Pi <- t(apply(Pi, 1, pi_gen, K = K))
  Theta <- matrix(runif(J * K), ncol = K)
  M <- matrix(rnorm(W * K, 0, 1), nrow = W)
  Pi[1:K, ] <- diag(rep(1, K))

  A_t <- Pi %*% t(Theta)
  X_t <- Pi %*% t(M)

  A <- matrix(rbinom(N * J, 1, A_t), nrow = N)
  X <- X_t + matrix(rnorm(N * W, 0, .5), nrow = N)
  X <- apply(X, 2, scale)

  GoM_simulate(A, X, K, Pi, Theta)
}

save.image("GoM_simulation.RData")
